
Backend:
  - backend/**/*

Frontend:
  - frontend/**/*
  - '!frontend/cypress/**/*'

e2e-tests:
  - frontend/cypress/**/*

DevOps:
  - .github/**/*
  - docker-compose.yml
  - '**/Dockerfile'


dependencies:
  - backend/build.gradle*
  - frontend/package.json