spring.datasource.url=jdbc:postgresql://db:5432/B2B_db
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=${JWT_EXPIRATION}