spring.datasource.url=jdbc:postgresql://localhost:5432/yourdb
spring.datasource.username=youruser
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update

# Generate a secure Base64 secret: openssl rand -base64 64
jwt.secret=bg2ZKM0HcOmYr9pTthuApj1gB7gfsmsMpY6SEFwYy3D
jwt.expiration=86400000 