name: Docker and Cypress CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker compose
      run: docker compose up -d

  e2e-tests:
    needs: build 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start application using Docker Compose

        run: docker compose up -d --build

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend 
          
          wait-on: 'http://localhost:3000' 
          
          wait-on-timeout: 120 

      - name: Stop containers and clean up
        if: always()
        run: docker compose down